<a href="https://colab.research.google.com/github/namratawadekar42/uberprediction/blob/main/UBER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("https://raw.githubusercontent.com/knowledgeshelfit/uber_rides/master/taxi.csv")
df

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0             15     1800000           5800                      50   
1             15     1790000           6200                      50   
2             15     1780000           6400                      60   
3             25     1778000           6500                      60   
4             25     1750000           6550                      60   
5             25     1740000           6580                      70   
6             25     1725000           8200                      75   
7             30     1725000           8600                      75   
8             30     1720000           8800                      75   
9             30     1705000           9200                      80   
10            30     1710000           9630                      80   
11            40     1700000          10570                      80   
12            40     1695000          11330                      85   
13            40     1695000          11600                     100   
14            40     1690000          11800                     105   
15            40     1630000          11830                     105   
16            65     1640000          12650                     105   
17           102     1635000          13000                     110   
18            75     1630000          13224                     125   
19            75     1620000          13766                     130   
20            75     1615000          14010                     150   
21            80     1605000          14468                     155   
22            86     1590000          15000                     165   
23            98     1595000          15200                     175   
24            87     1590000          15600                     175   
25            77     1600000          16000                     190   
26            63     1610000          16200                     200   

    Numberofweeklyriders  
0                 192000  
1                 190400  
2                 191200  
3                 177600  
4                 176800  
5                 178400  
6                 180800  
7                 175200  
8                 174400  
9                 173920  
10                172800  
11                163200  
12                161600  
13                161600  
14                160800  
15                159200  
16                148800  
17                115696  
18                147200  
19                150400  
20                152000  
21                136000  
22                126240  
23                123888  
24                126080  
25                151680  
26                152800

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Priceperweek            27 non-null     int64
 1   Population              27 non-null     int64
 2   Monthlyincome           27 non-null     int64
 3   Averageparkingpermonth  27 non-null     int64
 4   Numberofweeklyriders    27 non-null     int64
dtypes: int64(5)
memory usage: 1.2 KB


In [ ]:
#input and output
x=df.iloc[:,0:4].values
x

array([[     15, 1800000,    5800,      50],
       [     15, 1790000,    6200,      50],
       [     15, 1780000,    6400,      60],
       [     25, 1778000,    6500,      60],
       [     25, 1750000,    6550,      60],
       [     25, 1740000,    6580,      70],
       [     25, 1725000,    8200,      75],
       [     30, 1725000,    8600,      75],
       [     30, 1720000,    8800,      75],
       [     30, 1705000,    9200,      80],
       [     30, 1710000,    9630,      80],
       [     40, 1700000,   10570,      80],
       [     40, 1695000,   11330,      85],
       [     40, 1695000,   11600,     100],
       [     40, 1690000,   11800,     105],
       [     40, 1630000,   11830,     105],
       [     65, 1640000,   12650,     105],
       [    102, 1635000,   13000,     110],
       [     75, 1630000,   13224,     125],
       [     75, 1620000,   13766,     130],
       [     75, 1615000,   14010,     150],
       [     80, 1605000,   14468,     155],
       [  

In [ ]:
y=df.iloc[:,4].values
y

array([192000, 190400, 191200, 177600, 176800, 178400, 180800, 175200,
       174400, 173920, 172800, 163200, 161600, 161600, 160800, 159200,
       148800, 115696, 147200, 150400, 152000, 136000, 126240, 123888,
       126080, 151680, 152800])

In [ ]:
#train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([188629.50339543, 136559.39301861, 167923.33044203, 126048.35876704,
       178953.09696641, 166223.49873765, 130975.62779069, 167971.3136973 ,
       141866.03727522])

In [ ]:
train_score=model.score(x_train,y_train)*100
train_score

94.28364724316813

In [ ]:
test_score=model.score(x_test,y_test)*100
test_score

91.57379222488221

In [ ]:
#create model/save model
import joblib
joblib.dump(model,'ola')

['ola']

In [ ]:
#loading model
mymodel=joblib.load("/content/ola")

In [ ]:
model.predict([[15,	1800000	,5800	,50	]])

array([190038.04651918])